# Generated by Django 5.0.12 on 2025-02-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bet",
            unique_together={("race", "driver")},
        ),
    ]
