# Generated by Django 5.0.12 on 2025-02-26 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0002_alter_bet_unique_together"),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name="driver",
    #         name="team",
    #         field=models.ForeignKey(
    #             null=True,
    #             on_delete=django.db.models.deletion.CASCADE,
    #             to="commissioner.team",
    #         ),
    #     ),
    # ]
