# Generated by Django 5.0.12 on 2025-02-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0003_driver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="date created"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date last updated"
                    ),
                ),
                ("team", models.CharField(max_length=64, null=True)),
                ("manufacturer", models.CharField(max_length=64, null=True)),
                ("start_pos", models.IntegerField(default=-1)),
                ("finish_pos", models.IntegerField(default=-1)),
                ("car_no", models.IntegerField(default=-1)),
                ("laps", models.IntegerField(default=11)),
                ("start", models.IntegerField(default=-1)),
                ("led", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("bonus", models.IntegerField(default=0)),
                ("penality", models.IntegerField(default=0)),
                ("practice_pos", models.IntegerField(default=0)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commissioner.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commissioner.race",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
