# Generated by Django 5.0.12 on 2025-02-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0003_alter_driver_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="team",
        ),
    ]
