# Generated by Django 5.0.12 on 2025-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0005_driver_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="website",
            field=models.URLField(max_length=128, null=True, unique=True),
        ),
    ]
