# Generated by Django 5.0.12 on 2025-02-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0006_team_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="slug",
        ),
    ]
