# Generated by Django 5.0.12 on 2025-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0006_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="finish",
            field=models.IntegerField(default=-1),
        ),
    ]
