# Generated by Django 5.0.12 on 2025-02-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0007_bet_finish"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="slug",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name="RaceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="date created"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date last updated"
                    ),
                ),
                (
                    "src_dir",
                    models.CharField(
                        default="C:\\Users\\me\\Documents\\VisualCodeSource\\beerme2_db\\scripts\\csv_data\\",
                        max_length=128,
                    ),
                ),
                ("contents", models.CharField(default="race_results", max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
