# Generated by Django 5.0.12 on 2025-02-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0008_remove_race_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="country",
            field=models.CharField(default="USA", max_length=32, null=True),
        ),
    ]
