# Generated by Django 5.0.12 on 2025-02-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0008_driver_slug_driver_website_alter_driver_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
