# Generated by Django 5.0.12 on 2025-02-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissioner", "0009_alter_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="team",
            field=models.TextField(blank=True),
        ),
    ]
