# Generated by Django 5.0.12 on 2025-02-28 18:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0009_state_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="beers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_date",
            field=models.DateField(default=datetime.date(2025, 2, 28)),
        ),
        migrations.CreateModel(
            name="ScoreBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="date created"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commissioner.bet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
