# Generated by Django 5.0.12 on 2025-02-23 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissioner", "0010_driver_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bet",
            constraint=models.UniqueConstraint(
                fields=("race", "player", "driver"), name="name of constraint"
            ),
        ),
    ]
