# Generated by Django 5.0.12 on 2025-02-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0010_player_beers_alter_race_race_date_scoreboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreboard",
            name="race",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="commissioner.race",
            ),
        ),
    ]
