# Generated by Django 5.0.12 on 2025-02-24 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0011_bet_name_of_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bet",
            name="name of constraint",
        ),
        migrations.AddConstraint(
            model_name="bet",
            constraint=models.UniqueConstraint(
                fields=("race", "player", "driver"), name="unique_bet"
            ),
        ),
    ]
