# Generated by Django 5.0.12 on 2025-02-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0012_alter_race_race_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoreboard",
            name="winner",
        ),
    ]
