# Generated by Django 5.0.12 on 2025-02-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0012_remove_bet_name_of_constraint_bet_unique_bet"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bet",
            name="unique_bet",
        ),
        migrations.AlterUniqueTogether(
            name="bet",
            unique_together={("race", "player", "driver")},
        ),
    ]
