# Generated by Django 5.0.12 on 2025-02-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0013_remove_scoreboard_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreboard",
            name="looser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="commissioner.bet",
            ),
        ),
        migrations.AddField(
            model_name="scoreboard",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="commissioner.bet",
            ),
        ),
    ]
