# Generated by Django 5.0.12 on 2025-02-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0013_remove_bet_unique_bet_alter_bet_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bet",
            unique_together={("race", "driver")},
        ),
    ]
