# Generated by Django 5.0.12 on 2025-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0014_scoreboard_looser_scoreboard_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="short_name",
            field=models.CharField(default="N/A", max_length=16, null=True),
        ),
    ]
