# Generated by Django 5.0.12 on 2025-03-25 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0015_track_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="road_course",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="race",
            name="name",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_date",
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
