# Generated by Django 5.0.12 on 2025-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0017_tracktype_track_track_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5
            ),
        ),
    ]
