# Generated by Django 5.0.12 on 2025-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0019_alter_track_length_alter_track_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracktype",
            name="track_type",
            field=models.CharField(default="", max_length=32, null=True),
        ),
    ]
