# Generated by Django 5.0.12 on 2025-03-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0022_remove_driver_team_alter_driver_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivercurrentteam",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
