# Generated by Django 5.0.12 on 2025-03-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0023_alter_drivercurrentteam_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivercurrentteam",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
