# Generated by Django 5.0.12 on 2025-03-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0025_racingseries_drivercurrentteam_racing_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racingseries",
            name="name",
            field=models.CharField(default="NASCAR", max_length=32),
        ),
    ]
