# Generated by Django 5.0.12 on 2025-04-01 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0026_alter_racingseries_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="comments",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="teams",
            field=models.ManyToManyField(
                related_name="teams",
                through="commissioner.DriverCurrentTeam",
                to="commissioner.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="drivercurrentteam",
            constraint=models.UniqueConstraint(
                fields=("driver", "team", "racing_series", "start_date"),
                name="unique_driver_team_racing_series",
            ),
        ),
    ]
