# Generated by Django 5.0.12 on 2025-04-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0027_driver_comments_alter_driver_teams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="series",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="commissioner.racingseries",
            ),
            preserve_default=False,
        ),
    ]
