# Generated by Django 5.0.12 on 2025-04-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioner", "0028_race_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreboard",
            name="beers",
            field=models.IntegerField(default=0),
        ),
    ]
