-- Table: public.commissioner_raceresult

-- DROP TABLE IF EXISTS public.commissioner_raceresult;

CREATE TABLE IF NOT EXISTS public.commissioner_raceresult
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    team character varying(64) COLLATE pg_catalog."default",
    manufacturer character varying(64) COLLATE pg_catalog."default",
    start_pos integer NOT NULL,
    finish_pos integer NOT NULL,
    car_no integer NOT NULL,
    laps integer NOT NULL,
    start integer NOT NULL,
    led integer NOT NULL,
    points integer NOT NULL,
    bonus integer NOT NULL,
    penality integer NOT NULL,
    practice_pos integer NOT NULL,
    driver_id bigint NOT NULL,
    race_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT commissioner_raceresult_pkey PRIMARY KEY (id),
    CONSTRAINT commissioner_raceres_driver_id_b9f1150a_fk_commissio FOREIGN KEY (driver_id)
        REFERENCES public.commissioner_driver (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_raceres_race_id_8c9be5a6_fk_commissio FOREIGN KEY (race_id)
        REFERENCES public.commissioner_race (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_raceresult_user_id_7717acf4_fk_auth_user_id FOREIGN KEY (user_id)
        REFERENCES public.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.commissioner_raceresult
    OWNER to bob;
-- Index: commissioner_raceresult_driver_id_b9f1150a

-- DROP INDEX IF EXISTS public.commissioner_raceresult_driver_id_b9f1150a;

CREATE INDEX IF NOT EXISTS commissioner_raceresult_driver_id_b9f1150a
    ON public.commissioner_raceresult USING btree
    (driver_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_raceresult_race_id_8c9be5a6

-- DROP INDEX IF EXISTS public.commissioner_raceresult_race_id_8c9be5a6;

CREATE INDEX IF NOT EXISTS commissioner_raceresult_race_id_8c9be5a6
    ON public.commissioner_raceresult USING btree
    (race_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_raceresult_user_id_7717acf4

-- DROP INDEX IF EXISTS public.commissioner_raceresult_user_id_7717acf4;

CREATE INDEX IF NOT EXISTS commissioner_raceresult_user_id_7717acf4
    ON public.commissioner_raceresult USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;