-- Table: public.commissioner_driver

-- DROP TABLE IF EXISTS public.commissioner_driver;

CREATE TABLE IF NOT EXISTS public.commissioner_driver
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    website character varying(200) COLLATE pg_catalog."default",
    user_id integer NOT NULL,
    salary numeric(6,0),
    salary_currency character varying(3) COLLATE pg_catalog."default",
    comments text COLLATE pg_catalog."default",
    CONSTRAINT commissioner_driver_pkey PRIMARY KEY (id),
    CONSTRAINT commissioner_driver_name_key UNIQUE (name),
    CONSTRAINT commissioner_driver_user_id_95b3e13b_fk_auth_user_id FOREIGN KEY (user_id)
        REFERENCES public.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.commissioner_driver
    OWNER to bob;
-- Index: commissioner_driver_name_2c603e69_like

-- DROP INDEX IF EXISTS public.commissioner_driver_name_2c603e69_like;

CREATE INDEX IF NOT EXISTS commissioner_driver_name_2c603e69_like
    ON public.commissioner_driver USING btree
    (name COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_driver_user_id_95b3e13b

-- DROP INDEX IF EXISTS public.commissioner_driver_user_id_95b3e13b;

CREATE INDEX IF NOT EXISTS commissioner_driver_user_id_95b3e13b
    ON public.commissioner_driver USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;