-- Table: public.commissioner_player

-- DROP TABLE IF EXISTS public.commissioner_player;

CREATE TABLE IF NOT EXISTS public.commissioner_player
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    name character varying(64) COLLATE pg_catalog."default",
    user_id integer NOT NULL,
    beers integer NOT NULL,
    CONSTRAINT commissioner_player_pkey PRIMARY KEY (id),
    CONSTRAINT commissioner_player_name_key UNIQUE (name),
    CONSTRAINT commissioner_player_user_id_0ec95497_fk_auth_user_id FOREIGN KEY (user_id)
        REFERENCES public.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.commissioner_player
    OWNER to bob;
-- Index: commissioner_player_name_f19f8567_like

-- DROP INDEX IF EXISTS public.commissioner_player_name_f19f8567_like;

CREATE INDEX IF NOT EXISTS commissioner_player_name_f19f8567_like
    ON public.commissioner_player USING btree
    (name COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_player_user_id_0ec95497

-- DROP INDEX IF EXISTS public.commissioner_player_user_id_0ec95497;

CREATE INDEX IF NOT EXISTS commissioner_player_user_id_0ec95497
    ON public.commissioner_player USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;