-- Table: public.commissioner_bet

-- DROP TABLE IF EXISTS public.commissioner_bet;

CREATE TABLE IF NOT EXISTS public.commissioner_bet
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    finish integer NOT NULL,
    user_id integer NOT NULL,
    driver_id bigint NOT NULL,
    player_id bigint NOT NULL,
    race_id bigint NOT NULL,
    CONSTRAINT commissioner_bet_pkey PRIMARY KEY (id),
    CONSTRAINT commissioner_bet_race_id_driver_id_375de78e_uniq UNIQUE (race_id, driver_id),
    CONSTRAINT commissioner_bet_driver_id_06809569_fk_commissioner_driver_id FOREIGN KEY (driver_id)
        REFERENCES public.commissioner_driver (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_bet_player_id_de8f9974_fk_commissioner_player_id FOREIGN KEY (player_id)
        REFERENCES public.commissioner_player (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_bet_race_id_b091489e_fk_commissioner_race_id FOREIGN KEY (race_id)
        REFERENCES public.commissioner_race (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_bet_user_id_175b123f_fk_auth_user_id FOREIGN KEY (user_id)
        REFERENCES public.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.commissioner_bet
    OWNER to bob;
-- Index: commissioner_bet_driver_id_06809569

-- DROP INDEX IF EXISTS public.commissioner_bet_driver_id_06809569;

CREATE INDEX IF NOT EXISTS commissioner_bet_driver_id_06809569
    ON public.commissioner_bet USING btree
    (driver_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_bet_player_id_de8f9974

-- DROP INDEX IF EXISTS public.commissioner_bet_player_id_de8f9974;

CREATE INDEX IF NOT EXISTS commissioner_bet_player_id_de8f9974
    ON public.commissioner_bet USING btree
    (player_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_bet_race_id_b091489e

-- DROP INDEX IF EXISTS public.commissioner_bet_race_id_b091489e;

CREATE INDEX IF NOT EXISTS commissioner_bet_race_id_b091489e
    ON public.commissioner_bet USING btree
    (race_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_bet_user_id_175b123f

-- DROP INDEX IF EXISTS public.commissioner_bet_user_id_175b123f;

CREATE INDEX IF NOT EXISTS commissioner_bet_user_id_175b123f
    ON public.commissioner_bet USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;