-- Table: public.commissioner_race

-- DROP TABLE IF EXISTS public.commissioner_race;

CREATE TABLE IF NOT EXISTS public.commissioner_race
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    race_date date NOT NULL,
    laps integer NOT NULL,
    reload boolean NOT NULL,
    create_results_file boolean NOT NULL,
    user_id integer NOT NULL,
    track_id bigint,
    road_course boolean NOT NULL,
    series_id bigint NOT NULL,
    CONSTRAINT commissioner_race_pkey PRIMARY KEY (id),
    CONSTRAINT commissioner_race_race_date_95530d51_uniq UNIQUE (race_date),
    CONSTRAINT commissioner_race_series_id_98a76a36_fk_commissio FOREIGN KEY (series_id)
        REFERENCES public.commissioner_racingseries (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_race_track_id_e391071e_fk_commissioner_track_id FOREIGN KEY (track_id)
        REFERENCES public.commissioner_track (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_race_user_id_f701fe05_fk_auth_user_id FOREIGN KEY (user_id)
        REFERENCES public.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.commissioner_race
    OWNER to bob;
-- Index: commissioner_race_series_id_98a76a36

-- DROP INDEX IF EXISTS public.commissioner_race_series_id_98a76a36;

CREATE INDEX IF NOT EXISTS commissioner_race_series_id_98a76a36
    ON public.commissioner_race USING btree
    (series_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_race_track_id_e391071e

-- DROP INDEX IF EXISTS public.commissioner_race_track_id_e391071e;

CREATE INDEX IF NOT EXISTS commissioner_race_track_id_e391071e
    ON public.commissioner_race USING btree
    (track_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_race_user_id_f701fe05

-- DROP INDEX IF EXISTS public.commissioner_race_user_id_f701fe05;

CREATE INDEX IF NOT EXISTS commissioner_race_user_id_f701fe05
    ON public.commissioner_race USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;