-- Table: public.commissioner_drivercurrentteam

-- DROP TABLE IF EXISTS public.commissioner_drivercurrentteam;

CREATE TABLE IF NOT EXISTS public.commissioner_drivercurrentteam
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    start_date date NOT NULL,
    end_date date,
    driver_id bigint NOT NULL,
    team_id bigint NOT NULL,
    user_id integer NOT NULL,
    racing_series_id bigint,
    CONSTRAINT commissioner_drivercurrentteam_pkey PRIMARY KEY (id),
    CONSTRAINT unique_driver_team_racing_series UNIQUE (driver_id, team_id, racing_series_id, start_date),
    CONSTRAINT commissioner_driverc_driver_id_922dae1b_fk_commissio FOREIGN KEY (driver_id)
        REFERENCES public.commissioner_driver (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_driverc_racing_series_id_18a43848_fk_commissio FOREIGN KEY (racing_series_id)
        REFERENCES public.commissioner_racingseries (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_driverc_team_id_9967689b_fk_commissio FOREIGN KEY (team_id)
        REFERENCES public.commissioner_team (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT commissioner_drivercurrentteam_user_id_84541bce_fk_auth_user_id FOREIGN KEY (user_id)
        REFERENCES public.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.commissioner_drivercurrentteam
    OWNER to bob;
-- Index: commissioner_drivercurrentteam_driver_id_922dae1b

-- DROP INDEX IF EXISTS public.commissioner_drivercurrentteam_driver_id_922dae1b;

CREATE INDEX IF NOT EXISTS commissioner_drivercurrentteam_driver_id_922dae1b
    ON public.commissioner_drivercurrentteam USING btree
    (driver_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_drivercurrentteam_racing_series_id_18a43848

-- DROP INDEX IF EXISTS public.commissioner_drivercurrentteam_racing_series_id_18a43848;

CREATE INDEX IF NOT EXISTS commissioner_drivercurrentteam_racing_series_id_18a43848
    ON public.commissioner_drivercurrentteam USING btree
    (racing_series_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_drivercurrentteam_team_id_9967689b

-- DROP INDEX IF EXISTS public.commissioner_drivercurrentteam_team_id_9967689b;

CREATE INDEX IF NOT EXISTS commissioner_drivercurrentteam_team_id_9967689b
    ON public.commissioner_drivercurrentteam USING btree
    (team_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: commissioner_drivercurrentteam_user_id_84541bce

-- DROP INDEX IF EXISTS public.commissioner_drivercurrentteam_user_id_84541bce;

CREATE INDEX IF NOT EXISTS commissioner_drivercurrentteam_user_id_84541bce
    ON public.commissioner_drivercurrentteam USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;