-- Database: beer_me
SELECT
	TRACK."name",
	RACE.RACE_DATE
FROM
	COMMISSIONER_RACE RACE,
	COMMISSIONER_TRACK TRACK
WHERE
	TRACK.ID = RACE.TRACK_ID
	AND TRACK.NAME LIKE ('Mich%')
ORDER BY
	TRACK."name",
	RACE.RACE_DATE