-- Database: beer_me
SELECT
	TRACK."name",
	RACE.RACE_DATE
FROM
	COMMISSIONER_RACE RACE,
	COMMISSIONER_TRACK TRACK
WHERE
	TRACK.ID = RACE.TRACK_ID
	and race_date  > '2023-01-01' and race_date < '2024-01-01'
	-- AND TRACK.NAME LIKE ('Mich%')
ORDER BY
	-- TRACK."name",
	RACE.RACE_DATE