SELECT
	TRACK.NAME,
	TRACK.ID,
	RACE_DATE
FROM
	COMMISSIONER_RACE RACE,
	COMMISSIONER_RACERESULT RESULTS,
	COMMISSIONER_TRACK TRACK
WHERE
	RACE.TRACK_ID = TRACK.ID
	AND RACE.ID NOT IN (
		SELECT
			RACE_ID
		FROM
			COMMISSIONER_RACERESULT RESULTS
		WHERE
			RESULTS.RACE_ID = RACE.ID
	)
	AND RACE.RACE_DATE <= NOW()
GROUP BY
	TRACK.NAME,
	TRACK.ID,
	RACE_DATE
ORDER BY
	RACE.RACE_DATE DESC