-- Active: 1740417427513@@127.0.0.1@5432@beer_me@public
SELECT
	DRIVER.NAME,
	ROUND(AVG(RACERESULT.START_POS), 1) AVG_START,
	ROUND(AVG(FINISH_POS), 1) AVG_FINISH,
	COUNT(*) AS "races",
	CAST(DRIVER.SALARY AS MONEY),
	TEAM.NAME
FROM
	COMMISSIONER_DRIVER DRIVER,
	COMMISSIONER_RACERESULT RACERESULT,
	COMMISSIONER_RACE RACE,
	COMMISSIONER_DRIVERCURRENTTEAM DRIVER_TEAM,
	COMMISSIONER_TEAM TEAM,
	COMMISSIONER_TRACK TRACK
WHERE
	RACERESULT.RACE_ID = RACE.ID
	AND RACE.TRACK_ID = TRACK.ID
	AND RACERESULT.DRIVER_ID = DRIVER.ID
	AND DRIVER_TEAM.DRIVER_ID = DRIVER.ID
	AND DRIVER_TEAM.TEAM_ID = TEAM.ID
	AND DRIVER_TEAM.RACING_SERIES_ID = 1 -- NASCAR
	AND DRIVER_TEAM.END_DATE IS NULL -- not retired
	AND TRACK.name like('Talla%')
GROUP BY
	DRIVER.NAME,
	TEAM.NAME,
	SALARY
ORDER BY
	AVG_FINISH,
	AVG_START