SELECT
	FINISH_POS,
	BET.RACE_ID,
	PLAYER_ID
FROM
	COMMISSIONER_RACERESULT RACERESULT,
	COMMISSIONER_BET BET
WHERE
	BET.DRIVER_ID = RACERESULT.DRIVER_ID
	AND BET.RACE_ID = RACERESULT.RACE_ID
	AND FINISH_POS = (
		SELECT
			MIN(FINISH_POS)
		FROM
			COMMISSIONER_RACERESULT R,
			COMMISSIONER_BET B
		WHERE
			B.RACE_ID = R.RACE_ID
			AND R.DRIVER_ID = B.DRIVER_ID
			AND RACERESULT.RACE_ID = B.RACE_ID
	)
GROUP BY
	1,
	2,
	3