
SELECT
	DRIVER.NAME,
	RESULTS.CAR_NO,
	RESULTS.FINISH_POS,
	RESULTS.START_POS,
	RESULTS.MANUFACTURER
FROM
	COMMISSIONER_RACE AS RACE,
	COMMISSIONER_RACERESULT AS RESULTS,
	COMMISSIONER_DRIVER AS DRIVER
WHERE
	RACE.RACE_DATE = '2024-03-03'
	AND RACE.ID = RESULTS.RACE_ID
	AND RESULTS.DRIVER_ID = DRIVER.ID
ORDER BY
	RESULTS.FINISH_POS